#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var config = require('./package.json')
var program = require('commander')
var match = require('./')

program
  .version(config.version)
  .option('-d, --data [path]', 'input data path')
  .option('-o, --output [directory]', 'output directory')
  .option('-t, --threshold [number]', 'threshold')
  .parse(process.argv)

fs.readFile(program.data, (fsReadFileError, data) => {
  if (fsReadFileError) throw new Error(fsReadFileError)

  try {
    data = JSON.parse(data)
  } catch (jsonParseError) {
    throw new Error(jsonParseError)
  }

  console.log('Working...')
  match(data, program.threshold, (matchError, ratios) => {
    if (matchError) throw new Error(matchError)
    var duplicateFeatures = data.features.map((f, i) => Object.assign(f, { ratio: ratios[i] }))
      .filter(f => f.ratio < 0.9)
    var output = { type: 'FeatureCollection', features: duplicateFeatures }
    console.log('Done!', duplicateFeatures.length, 'lines had duplicates')
    var out = path.join(__dirname, (program.output || '.'), 'duplicates.geojson')
    console.log('Writing', out)
    fs.writeFile(out, JSON.stringify(output), (fsWriteFileError) => {
      if (fsWriteFileError) throw new Error(fsWriteFileError)
    })
  })
})
